/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package br.hikarikun92.swaggerbase.rest.api;

import br.hikarikun92.swaggerbase.rest.model.Person;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@Api(value = "person", description = "the person API")
public interface PersonApi {

    Logger log = LoggerFactory.getLogger(PersonApi.class);

    default Optional<ObjectMapper> getObjectMapper(){
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest(){
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Lists the people registered in the system", nickname = "findAll", notes = "Lists all the people registered in the system", response = Person.class, responseContainer = "List", tags={ "person", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "If the search was successful", response = Person.class, responseContainer = "List"),
        @ApiResponse(code = 500, message = "If an internal error happened") })
    @RequestMapping(value = "/person",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<Person>> _findAll() {
        return findAll();
    }

    // Override this method
    default ResponseEntity<List<Person>> findAll() {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {\r\n  \"nationality\" : \"nationality\",\r\n  \"name\" : \"name\",\r\n  \"birthDate\" : \"2000-01-23\",\r\n  \"email\" : \"\"\r\n}, {\r\n  \"nationality\" : \"nationality\",\r\n  \"name\" : \"name\",\r\n  \"birthDate\" : \"2000-01-23\",\r\n  \"email\" : \"\"\r\n} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default PersonApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
